### PR TITLE
Clarification of copyright notice.

### PR DESCRIPTION
**Pull request by edwarnicke**
I corresponded with the Airspace theme author about
clarifying the copyright notice in the footer.
I'll add him to the patch review.

### CODE REVIEW

**Comment by edwarnicke** [comment]
@kausarpial - Does this look good to you?

**Comment by edwarnicke** [comment]
Lets hold this patch till @kausarpial weighs in :)

**Comment by edwarnicke** [comment]
@mehedi-sharif does this look good to you?

**Comment by mehedi-sharif** [comment]
Obviously .

**Comment by edwarnicke** [comment]
@mehedi-sharif Many thanks :)

@mestery @fkautz  The theme author is @mehedi-sharif, so he's now blessed this footer clarification.

**Comment by mehedi-sharif** [comment]
If you want you can change the copyright text with yours .  Even you dont need to put the link back to the theme. 
Thanks

**Comment by edwarnicke** [comment]
@mehedi-sharif - You do good work, you deserve credit :)

**Pull request merged**
